# Generated by Django 3.2.12 on 2022-03-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['createdAt']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='createdAt',
        ),
    ]
