# Generated by Django 4.0.3 on 2022-03-15 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_vote_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='vote',
        ),
        migrations.AddField(
            model_name='choice',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='board.board'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='text',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
