# Generated by Django 4.0.3 on 2022-03-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='boardList',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
