# Generated by Django 3.2.12 on 2022-03-30 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Love', 'Love'), ('Travel', 'Travel'), ('Fashion', 'Fashion')], max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('likeCount', models.IntegerField(default=0)),
                ('votedIndex', models.IntegerField(default=-1)),
                ('voteText', models.CharField(max_length=200)),
                ('liker', models.ManyToManyField(related_name='liker_board', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_board', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('indexInBoard', models.IntegerField(default=0)),
                ('boardId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_board_id', to='boards.board')),
                ('voter', models.ManyToManyField(related_name='voter_board', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['boardId'],
            },
        ),
    ]
