# Generated by Django 4.0.3 on 2022-03-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(choices=[('Love', 'Love'), ('Travel', 'Travel'), ('Fashion', 'Fashion')], max_length=10),
        ),
    ]
